language: csharp
solution: EzbAdapter/EzbAdapter.sln
install:
  - nuget restore EzbAdapter/EzbAdapter.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release EzbAdapter/EzbAdapter.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./EzbAdapter/EzbAdapter.Test/bin/Release/EzbAdapter.Test.dll